version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit
    working_dir: '/app'
    tty: true
    volumes:
        - ./app:/app
    ports:
        - '8501:8501'
    command: streamlit run main.py
    env_file: .env